# Generated by Django 3.2.11 on 2022-03-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_venue_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approver',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
    ]
