# Generated by Django 3.2.11 on 2022-03-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_approver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='approver',
        ),
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
